### ISSUE TITLE
Adding and removing admin user right messes user access

### ISSUE THREAD

**Issue by arihakala** [prove/tarantula#20]
See:

https://getsatisfaction.com/prove/topics/non_admin_users_see_nothing

I think this is related to way Tarantula opens to last active project when logging in. If user no longer has access to that project (due removed admin rights), user cannot do anything (not even change to project to which he has access).

**Comment by iiska** [comment]
This 099426014876b5f239d0803654ff9eb976421fd9 probably fixes the issue.
