### ISSUE TITLE
Backup task fails (old paths should be replaced with new)

### ISSUE THREAD

**Issue by arihakala** [prove/tarantula#3]
RAILS_ENV=production bundle exec rake db:backup
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
Port could not be introspected; we must not be running Mongrel in this instance.
/usr/bin/env mysqldump -uroot ... [password filtered]
/usr/bin/env mysqldump -uroot  testia > /opt/testia/backup/tarantula/daily.sql
sh: /opt/testia/backup/tarantula/daily.sql: No such file or directory
rake aborted!
Command failed with status (1): [/usr/bin/env mysqldump -uroot  testia > /o...]

Tasks: TOP => db:backup

**Comment by ander** [comment]
changed default daily backup directory to /opt/tarantula
