### ISSUE TITLE
Links that are displayed in the textfields' values (when viewing and not editing entities) should be clickable

### ISSUE THREAD

**Issue by AdamHepner** [prove/tarantula#31]
This would allow easy, although one way, integration of Tarantula with many external services

**Comment by iiska** [comment]
Larger textareas in Case design, Requirements design and Testobjects design are now implemented to convert urls to clickable links when inputs are in read-only mode.

I'm working to implement this change to Test section also.

**Comment by iiska** [comment]
Urls in Test section should be clickable now.
