### ISSUE TITLE
Firewall blocks install script

### ISSUE THREAD

**Issue by arihakala** [prove/tarantula#4]
Install and update scripts should be changed to use https protocol instead of git protocol. (by default or as option?)

**Comment by alexboss** [comment]
Thank you for the resolution of this issue guys !

I finally managed to install Tanrantula behind a firewall on Red Hat EL Server 6.3 Santiago (x86_64) using the following tutorial http://www.testiatarantula.com/install-on-linux/  (even if it was a pain in the a*\* to make it work behind a proxy, requiring to configure the proxy values in ~/.bashrc + ~/.curlrc + ~/.gemrc)

Alexandre 8)
