### ISSUE TITLE
Protocol, host, and port information for configuration

### ISSUE THREAD

**Issue by kirantpatil** [prove/tarantula#43]
System setup:
[root@fedora17 rails]# uname -a
Linux fedora17 3.3.4-5.fc17.x86_64 #1 SMP Mon May 7 17:29:34 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

For below option, what are the values do we need to provide.
I provided only 'http://yourdomain.com' and it gave the below error.
Please let us know what values do we need to provide for Protocol, host, port combination ? 
Is it something like (tcp, localhost, 80) ?

GENERAL
- Protocol, host, and port (e.g. 'http://yourdomain.com')
## All installation went fine except  following two steps,

[root@fedora17 rails]# yum install http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-7.noarch.rpm
Loaded plugins: langpacks, presto, refresh-packagekit
epel-release-6-7.noarch.rpm                             |  14 kB     00:00  
Examining /var/tmp/yum-root-yrIrYu/epel-release-6-7.noarch.rpm: epel-release-6-7.noarch
Marking /var/tmp/yum-root-yrIrYu/epel-release-6-7.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:6-7 will be installed
--> Processing Conflict: epel-release-6-7.noarch conflicts fedora-release
No package matched to upgrade: epel-release
--> Finished Dependency Resolution
Error: epel-release conflicts with fedora-release-17-1.noarch
 You could try using --skip-broken to work around the problem
##  You could try running: rpm -Va --nofiles --nodigest

[root@fedora17 rails]# RAILS_ENV=production rake tarantula:install
testia already exists
-- create_table("attachment_sets", {:force=>true})
   -> 0.2259s
-- create_table("attachment_sets_attachments", {:id=>false, :force=>true})
   -> 0.1106s
-- create_table("attachments", {:force=>true})
   -> 0.2126s
-- create_table("bug_components", {:force=>true})
   -> 0.1090s
-- add_index("bug_components", ["bug_product_id"], {:name=>"index_bug_components_on_bug_product_id"})
   -> 0.1772s
-- add_index("bug_components", ["external_id"], {:name=>"index_bug_components_on_external_id"})
   -> 0.2146s
-- create_table("bug_products", {:force=>true})
   -> 0.1279s
-- add_index("bug_products", ["bug_tracker_id"], {:name=>"index_bug_products_on_bug_tracker_id"})
   -> 0.2367s
-- add_index("bug_products", ["external_id"], {:name=>"index_bug_products_on_external_id"})
   -> 0.2110s
-- create_table("bug_products_projects", {:id=>false, :force=>true})
   -> 0.0991s
-- add_index("bug_products_projects", ["bug_product_id", "project_id"], {:name=>"index_bug_products_projects_on_bug_product_id_and_project_id"})
   -> 0.2149s
-- create_table("bug_products_test_areas", {:id=>false, :force=>true})
   -> 0.1280s
-- add_index("bug_products_test_areas", ["bug_product_id", "test_area_id"], {:name=>"index_bug_products_test_areas_on_bug_product_id_and_test_area_id"})
   -> 0.2536s
-- create_table("bug_severities", {:force=>true})
   -> 0.1188s
-- add_index("bug_severities", ["bug_tracker_id"], {:name=>"index_bug_severities_on_bug_tracker_id"})
   -> 0.1860s
-- add_index("bug_severities", ["external_id"], {:name=>"index_bug_severities_on_external_id"})
   -> 0.2452s
-- add_index("bug_severities", ["sortkey"], {:name=>"index_bug_severities_on_sortkey"})
   -> 0.1864s
-- create_table("bug_snapshots", {:force=>true})
   -> 0.1862s
-- add_index("bug_snapshots", ["bug_component_id"], {:name=>"index_bug_snapshots_on_bug_component_id"})
   -> 0.2200s
-- add_index("bug_snapshots", ["bug_id"], {:name=>"index_bug_snapshots_on_bug_id"})
   -> 0.1858s
-- add_index("bug_snapshots", ["bug_product_id"], {:name=>"index_bug_snapshots_on_bug_product_id"})
   -> 0.2446s
-- add_index("bug_snapshots", ["bug_severity_id"], {:name=>"index_bug_snapshots_on_bug_severity_id"})
   -> 0.1852s
-- add_index("bug_snapshots", ["bug_tracker_snapshot_id"], {:name=>"index_bug_snapshots_on_bug_tracker_snapshot_id"})
   -> 0.1940s
-- add_index("bug_snapshots", ["external_id"], {:name=>"index_bug_snapshots_on_external_id"})
   -> 0.2725s
-- add_index("bug_snapshots", ["lastdiffed"], {:name=>"index_bug_snapshots_on_lastdiffed"})
   -> 0.1948s
-- add_index("bug_snapshots", ["priority"], {:name=>"index_bug_snapshots_on_priority"})
   -> 0.2936s
-- add_index("bug_snapshots", ["status"], {:name=>"index_bug_snapshots_on_status"})
   -> 0.1753s
-- create_table("bug_tracker_snapshots", {:force=>true})
   -> 0.0934s
-- add_index("bug_tracker_snapshots", ["bug_tracker_id"], {:name=>"index_bug_tracker_snapshots_on_bug_tracker_id"})
   -> 0.2364s
-- create_table("bug_trackers", {:force=>true})
   -> 0.2366s
-- create_table("bugs", {:force=>true})
   -> 0.1358s
-- add_index("bugs", ["bug_component_id"], {:name=>"bugs_bug_component"})
   -> 0.1903s
-- add_index("bugs", ["bug_component_id"], {:name=>"index_bugs_on_bug_component_id"})
   -> 0.2788s
-- add_index("bugs", ["bug_product_id"], {:name=>"bugs_bug_product"})
   -> 0.7581s
-- add_index("bugs", ["bug_product_id"], {:name=>"index_bugs_on_bug_product_id"})
   -> 0.2735s
-- add_index("bugs", ["bug_severity_id"], {:name=>"bugs_bug_severity"})
   -> 0.4266s
-- add_index("bugs", ["bug_severity_id"], {:name=>"index_bugs_on_bug_severity_id"})
   -> 0.2184s
-- add_index("bugs", ["bug_tracker_id"], {:name=>"bugs_bug_tracker"})
   -> 0.1831s
-- add_index("bugs", ["bug_tracker_id"], {:name=>"index_bugs_on_bug_tracker_id"})
   -> 0.1900s
-- add_index("bugs", ["external_id"], {:name=>"index_bugs_on_external_id"})
   -> 0.1689s
-- add_index("bugs", ["id"], {:name=>"bugs_id", :unique=>true})
   -> 0.1971s
-- add_index("bugs", ["lastdiffed"], {:name=>"index_bugs_on_lastdiffed"})
   -> 0.2107s
-- add_index("bugs", ["priority"], {:name=>"index_bugs_on_priority"})
   -> 0.2370s
-- add_index("bugs", ["status"], {:name=>"index_bugs_on_status"})
   -> 0.1696s
-- create_table("case_avg_duration", {:id=>false, :force=>true})
   -> 0.1445s
-- create_table("case_executions", {:force=>true})
   -> 0.1300s
-- add_index("case_executions", ["case_id"], {:name=>"index_case_executions_on_case_id"})
   -> 0.1773s
-- add_index("case_executions", ["case_version"], {:name=>"index_case_executions_on_case_version"})
   -> 0.2704s
-- add_index("case_executions", ["executed_by"], {:name=>"index_case_executions_on_executed_by"})
   -> 0.1870s
-- add_index("case_executions", ["execution_id"], {:name=>"index_case_executions_on_execution_id"})
   -> 0.2126s
-- add_index("case_executions", ["result"], {:name=>"index_case_executions_on_result"})
   -> 0.1857s
-- create_table("case_versions", {:force=>true})
   -> 0.2374s
-- add_index("case_versions", ["case_id"], {:name=>"index_case_versions_on_case_id"})
   -> 0.1677s
-- add_index("case_versions", ["version"], {:name=>"index_case_versions_on_version"})
   -> 0.2110s
-- create_table("cases", {:force=>true})
   -> 0.1475s
-- add_index("cases", ["deleted"], {:name=>"index_cases_on_deleted"})
   -> 0.2113s
-- add_index("cases", ["id"], {:name=>"index_cases_on_id"})
   -> 0.2364s
-- add_index("cases", ["priority", "title"], {:name=>"index_cases_on_priority_and_title"})
   -> 0.1924s
-- add_index("cases", ["project_id"], {:name=>"index_cases_on_project_id"})
   -> 0.1693s
-- create_table("cases_requirements", {:id=>false, :force=>true})
   -> 0.2120s
-- create_table("cases_steps", {:id=>false, :force=>true})
   -> 0.1274s
-- add_index("cases_steps", ["case_id"], {:name=>"index_cases_steps_on_case_id"})
   -> 0.1362s
-- create_table("cases_test_areas", {:id=>false, :force=>true})
   -> 0.1856s
-- create_table("cases_test_sets", {:id=>false, :force=>true})
   -> 0.1359s
-- add_index("cases_test_sets", ["case_id"], {:name=>"index_cases_test_sets_on_case_id"})
   -> 0.1452s
-- add_index("cases_test_sets", ["case_version"], {:name=>"index_cases_test_sets_on_test_case_version"})
   -> 0.2699s
-- add_index("cases_test_sets", ["test_set_id"], {:name=>"index_cases_test_sets_on_test_set_id"})
   -> 0.1661s
-- add_index("cases_test_sets", ["test_set_version"], {:name=>"index_cases_test_sets_on_test_set_version"})
   -> 0.2168s
-- create_table("customer_configs", {:force=>true})
   -> 0.0943s
-- create_table("delayed_jobs", {:force=>true})
   -> 0.1325s
-- add_index("delayed_jobs", ["locked_by"], {:name=>"index_delayed_jobs_on_locked_by"})
   -> 0.1774s
-- create_table("executions", {:force=>true})
   -> 0.1939s
-- add_index("executions", ["deleted"], {:name=>"index_executions_on_deleted"})
   -> 0.1756s
-- add_index("executions", ["id"], {:name=>"index_executions_on_id"})
   -> 0.2084s
-- add_index("executions", ["project_id"], {:name=>"index_executions_on_project_id"})
   -> 0.1787s
-- add_index("executions", ["test_object_id"], {:name=>"index_executions_on_test_object_id"})
   -> 0.2594s
-- add_index("executions", ["test_set_id"], {:name=>"index_executions_on_test_set_id"})
   -> 0.1622s
-- add_index("executions", ["test_set_version"], {:name=>"index_executions_on_test_set_version"})
   -> 0.1823s
-- create_table("executions_test_areas", {:id=>false, :force=>true})
   -> 0.1025s
-- create_table("import_sources", {:force=>true})
   -> 0.1317s
-- create_table("password_resets", {:force=>true})
   -> 0.1441s
-- create_table("preferences", {:force=>true})
   -> 0.1310s
-- create_table("project_assignments", {:force=>true})
   -> 0.1356s
-- create_table("projects", {:force=>true})
   -> 0.2012s
-- create_table("report_data", {:force=>true})
   -> 0.1357s
-- create_table("requirement_versions", {:force=>true})
   -> 0.1442s
-- create_table("requirements", {:force=>true})
   -> 0.1945s
-- add_index("requirements", ["external_id"], {:name=>"index_requirements_on_external_id"})
   -> 0.1695s
-- add_index("requirements", ["name"], {:name=>"index_requirements_on_name"})
   -> 0.2280s
-- add_index("requirements", ["project_id"], {:name=>"index_requirements_on_project_id"})
   -> 0.2366s
-- create_table("requirements_test_areas", {:id=>false, :force=>true})
   -> 0.1345s
-- create_table("step_executions", {:force=>true})
   -> 0.6770s
-- add_index("step_executions", ["case_execution_id"], {:name=>"index_step_executions_on_case_execution_id"})
   -> 0.3364s
-- add_index("step_executions", ["step_id"], {:name=>"index_step_executions_on_step_id"})
   -> 0.1672s
-- create_table("step_versions", {:force=>true})
   -> 0.1364s
-- add_index("step_versions", ["case_id"], {:name=>"index_step_versions_on_case_id"})
   -> 0.2210s
-- add_index("step_versions", ["step_id"], {:name=>"index_step_versions_on_step_id"})
   -> 0.1691s
-- create_table("steps", {:force=>true})
   -> 0.2567s
-- create_table("taggings", {:force=>true})
   -> 0.0998s
-- add_index("taggings", ["tag_id", "taggable_id", "taggable_type"], {:name=>"index_taggings_on_tag_id_and_taggable_id_and_taggable_type", :unique=>true})
   -> 0.2153s
-- add_index("taggings", ["tag_id"], {:name=>"index_taggings_on_tag_id"})
   -> 0.2013s
-- add_index("taggings", ["taggable_id"], {:name=>"index_taggings_on_taggable_id"})
   -> 0.2277s
-- add_index("taggings", ["taggable_type"], {:name=>"index_taggings_on_taggable_type"})
   -> 0.2445s
-- create_table("tags", {:force=>true})
   -> 0.1023s
-- add_index("tags", ["id"], {:name=>"index_tags_on_id"})
   -> 0.1856s
-- add_index("tags", ["name"], {:name=>"index_tags_on_name"})
   -> 0.2616s
-- create_table("tasks", {:force=>true})
   -> 0.1446s
-- create_table("test_areas", {:force=>true})
   -> 0.1864s
-- create_table("test_areas_test_objects", {:id=>false, :force=>true})
   -> 0.0775s
-- create_table("test_areas_test_sets", {:id=>false, :force=>true})
   -> 0.0939s
-- create_table("test_objects", {:force=>true})
   -> 0.1869s
-- add_index("test_objects", ["created_at"], {:name=>"index_test_objects_on_created_at"})
   -> 0.1860s
-- add_index("test_objects", ["date"], {:name=>"index_test_objects_on_date"})
   -> 0.1913s
-- add_index("test_objects", ["name"], {:name=>"index_test_objects_on_name"})
   -> 0.2280s
-- add_index("test_objects", ["project_id"], {:name=>"index_test_objects_on_project_id"})
   -> 0.2445s
-- create_table("test_set_versions", {:force=>true})
   -> 0.1353s
-- add_index("test_set_versions", ["test_set_id"], {:name=>"index_test_set_versions_on_test_set_id"})
   -> 0.1814s
-- create_table("test_sets", {:force=>true})
   -> 0.1359s
-- add_index("test_sets", ["priority", "name"], {:name=>"index_test_sets_on_priority_and_name"})
   -> 0.2869s
-- add_index("test_sets", ["project_id"], {:name=>"index_test_sets_on_project_id"})
   -> 0.1527s
-- create_table("users", {:force=>true})
   -> 0.1002s
-- initialize_schema_migrations_table()
   -> 0.0011s
-- assume_migrated_upto_version(20120905062740, ["/opt/tarantula/rails/db/migrate"])
   -> 0.0056s
/usr/local/rvm/rubies/ruby-1.9.3-p286/bin/ruby /usr/local/rvm/gems/ruby-1.9.3-p286@global/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets 

GENERAL
- Protocol, host, and port (e.g. 'http://yourdomain.com')

http://yourdomain.com

rake aborted!
undefined method `split' for nil:NilClass

Tasks: TOP => db:config:app
(See full trace by running task with --trace)

---

with trace,

/usr/local/rvm/rubies/ruby-1.9.3-p286/bin/ruby /usr/local/rvm/gems/ruby-1.9.3-p286@global/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
*\* Invoke assets:precompile:all (first_time)
*\* Execute assets:precompile:all
*\* Invoke assets:precompile:primary (first_time)
*\* Invoke assets:environment (first_time)
*\* Execute assets:environment
*\* Invoke environment (first_time)
*\* Execute environment
*\* Invoke tmp:cache:clear (first_time)
*\* Execute tmp:cache:clear
*\* Execute assets:precompile:primary
*\* Invoke assets:precompile:nondigest (first_time)
*\* Invoke assets:environment (first_time)
*\* Execute assets:environment
*\* Invoke environment (first_time)
*\* Execute environment
*\* Invoke tmp:cache:clear (first_time)
*\* Execute tmp:cache:clear
*\* Execute assets:precompile:nondigest
*\* Invoke environment 
*\* Execute tarantula:install
*\* Invoke db:config:app (first_time)
*\* Invoke environment 
*\* Execute db:config:app

GENERAL
- Protocol, host, and port (e.g. 'http://yourdomain.com')
  rake aborted!
  undefined method `split' for nil:NilClass
  /opt/tarantula/rails/lib/customerconfig/rake_helper.rb:52:in`ask_host_info'
  /opt/tarantula/rails/lib/tasks/db_config.rake:8:in `block (3 levels) in <top (required)>'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
  /usr/local/rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
  /opt/tarantula/rails/lib/tasks/install.rake:4:in`block (2 levels) in <top (required)>'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`block in execute'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`execute'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
  /usr/local/rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in`invoke'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block (2 levels) in top_level'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block in top_level'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in`top_level'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
  /opt/tarantula/rails/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in`<top (required)>'
  /usr/local/rvm/gems/ruby-1.9.3-p286@global/bin/rake:19:in `load'
  /usr/local/rvm/gems/ruby-1.9.3-p286@global/bin/rake:19:in`<main>'
  /usr/local/rvm/gems/ruby-1.9.3-p286/bin/ruby_noexec_wrapper:14:in `eval'
  /usr/local/rvm/gems/ruby-1.9.3-p286/bin/ruby_noexec_wrapper:14:in`<main>'
  Tasks: TOP => db:config:app

Thanks,
Kiran.

**Comment by kirantpatil** [comment]
it was really confusing on that step but got answer from below link,
https://getsatisfaction.com/prove/topics/install_failing

Thanks for great project.

Kiran Patil

**Comment by raresmr** [comment]
@kirantpatil How did you manage to solve this ?
